openapi: 3.0.0
info:
  title: Bulk Load data
  version: '1.0'
  description: |-
    This api allows to bulk load observations and related metadata such as, the session of data collection, the subject of data collection, and the producer that generated the data.

    This is a API is secured using oauth2 tokens. You need an oauth2 token in order to load data through the bulk load data endpoint. To get oauth2 tokens, you need to authenticate using a username and password supplied to the Get Authorization Keys endpoint using a basic http authentication header.
servers:
  - url: 'http://localhost:3000'
paths:
  /tokens:
    get:
      summary: Get Authorization Tokens
      tags: []
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: object
                    properties:
                      token:
                        type: string
                      expiresAt:
                        type: string
                  refreshToken:
                    type: object
                    properties:
                      token:
                        type: string
                      expiresAt:
                        type: string
              examples:
                example-token:
                  value:
                    accessToken:
                      token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ
                      expiresAt: '2020-02-14T17:04:35+0000'
                    refreshToken:
                      token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ
                      expiresAt: '2020-02-14T17:04:35+0000'
      operationId: get-tokens
      description: Get JWT access and refresh tokens. This requires valid credentials specied using a basic authentication header.
      requestBody: {}
      security:
        - Basic Authentication: []
  /data_sets:
    post:
      summary: Upload a data set
      operationId: post-data_sets
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataSet'
              examples:
                observations-without-session:
                  value:
                    id: de10dc43-764f-405d-bed5-5274bc941cb9
                    identifier: First DataSet
                    data_producer:
                      identifier: VR Vive
                    subject:
                      id: de10dc43-764f-405d-bed5-5274bc941cb6
                      identifier: eagle
                    observations:
                      - id: 1
                        identifier: round1CorrectShots
                        observedAt: '2020-02-14T17:04:35+0000'
                        valueInteger: 1
                      - id: 2
                        identifier: round1AverageTimeToDecide
                        observedAt: '2020-02-14T17:04:36+0000'
                        valueInteger: 1
                      - id: 3
                        identifier: round1ArousalAverage
                        observedAt: '2020-02-14T17:04:37+0000'
                        valueDecimal: 4.4
                      - id: 4
                        identifier: round1LowestArousal
                        observedAt: '2020-02-14T17:04:38+0000'
                        valueDecimal: 8.9
                      - id: 5
                        identifier: finalScore
                        observedAt: '2020-02-14T17:04:39+0000'
                        valueDecimal: 699
                observations with session:
                  value:
                    id: de10dc43-764f-405d-bed5-5274bc941cb9
                    identifier: First DataSet
                    data_producer:
                      identifier: VR Vive
                    subject:
                      id: de10dc43-764f-405d-bed5-5274bc941cb6
                      identifier: eagle
                    session:
                      id: 17a5f612-8d1d-4906-b5c1-ed9001ea1761
                      identifier: First Trial
                      startedAt: '2020-02-14T17:00:00+0000'
                      endedAt: '2020-02-14T17:11:35+0000'
                    observations:
                      - id: 1
                        identifier: round1CorrectShots
                        observedAt: '2020-02-14T17:04:35+0000'
                        valueInteger: 1
                      - id: 2
                        identifier: round1AverageTimeToDecide
                        observedAt: '2020-02-14T17:04:36+0000'
                        valueInteger: 1
                      - id: 3
                        identifier: round1ArousalAverage
                        observedAt: '2020-02-14T17:04:37+0000'
                        valueDecimal: 4.4
                      - id: 4
                        identifier: round1LowestArousal
                        observedAt: '2020-02-14T17:04:38+0000'
                        valueDecimal: 8.9
                      - id: 5
                        identifier: finalScore
                        observedAt: '2020-02-14T17:04:39+0000'
                        valueDecimal: 699
      description: |-
        Upload a data set. A data set is a collection of information including:
        1) The producer that generated the data
        2) The session withint which data was collected. This is optional.
        3) The subject of the data collection
        4) One or more observations collected

        This is a secure api call which requires an Authorization header that includes a bearer access token. For examples of payload and response, checkout the accompanied examples.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                data_producer:
                  type: object
                  required:
                    - identifier
                  properties:
                    identifier:
                      type: string
                session:
                  type: object
                  properties:
                    identifier:
                      type: string
                    description:
                      type: string
                    startedAt:
                      type: string
                    endedAt:
                      type: string
                    authoredBy:
                      type: string
                  required:
                    - identifier
                    - startedAt
                    - endedAt
                    - authoredBy
                subject:
                  type: object
                  required:
                    - identifier
                  properties:
                    identifier:
                      type: string
                    description:
                      type: string
                observations:
                  type: array
                  items:
                    type: object
                    properties:
                      identifier:
                        type: string
                        minLength: 1
                        maxLength: 100
                      valueDecimal:
                        type: number
                      valueInteger:
                        type: integer
                      valueString:
                        type: string
                      observedAt:
                        type: string
                        format: date-time
                    required:
                      - identifier
                      - observedAt
                identifier:
                  type: string
                  minLength: 1
                  maxLength: 100
              required:
                - data_producer
                - subject
                - observations
                - identifier
            examples:
              observations-data-without-session:
                value:
                  identifier: First DataSet
                  data_producer:
                    identifier: VR Vive
                  subject:
                    identifier: eagle
                  observations:
                    - identifier: round1CorrectShots
                      observedAt: '2020-02-14T17:04:35+0000'
                      valueInteger: 1
                    - identifier: round1AverageTimeToDecide
                      observedAt: '2020-02-14T17:04:36+0000'
                      valueInteger: 1
                    - identifier: round1ArousalAverage
                      observedAt: '2020-02-14T17:04:37+0000'
                      valueDecimal: 4.4
                    - identifier: round1LowestArousal
                      observedAt: '2020-02-14T17:04:38+0000'
                      valueDecimal: 8.9
                    - identifier: finalScore
                      observedAt: '2020-02-14T17:04:39+0000'
                      valueDecimal: 699
              observation-data-with-session:
                value:
                  identifier: First DataSet
                  data_producer:
                    identifier: VR Vive
                  subject:
                    identifier: eagle
                  session:
                    identifier: First Trial
                    startedAt: '2020-02-14T17:00:00+0000'
                    endedAt: '2020-02-14T17:11:35+0000'
                  observations:
                    - identifier: round1CorrectShots
                      observedAt: '2020-02-14T17:04:35+0000'
                      valueInteger: 1
                    - identifier: round1AverageTimeToDecide
                      observedAt: '2020-02-14T17:04:36+0000'
                      valueInteger: 1
                    - identifier: round1ArousalAverage
                      observedAt: '2020-02-14T17:04:37+0000'
                      valueDecimal: 4.4
                    - identifier: round1LowestArousal
                      observedAt: '2020-02-14T17:04:38+0000'
                      valueDecimal: 8.9
                    - identifier: finalScore
                      observedAt: '2020-02-14T17:04:39+0000'
                      valueDecimal: 699
        description: Bulk load data
      security:
        - Access Tokens: []
    parameters: []
components:
  schemas:
    DataSet:
      title: DataSet
      type: object
      description: A collection of observations for a given subject that was observed during a session.
      x-examples:
        observations-without-session:
          identifier: First DataSet
          data_producer:
            identifier: VR Vive
          subject:
            identifier: eagle
          observations:
            - identifier: round1CorrectShots
              observedAt: '2020-02-14T17:04:35+0000'
              valueInteger: 1
            - identifier: round1AverageTimeToDecide
              observedAt: '2020-02-14T17:04:36+0000'
              valueInteger: 1
            - identifier: round1ArousalAverage
              observedAt: '2020-02-14T17:04:37+0000'
              valueDecimal: 4.4
            - identifier: round1LowestArousal
              observedAt: '2020-02-14T17:04:38+0000'
              valueDecimal: 8.9
            - identifier: finalScore
              observedAt: '2020-02-14T17:04:39+0000'
              valueDecimal: 699
        observations-with-session:
          identifier: First DataSet
          data_producer:
            identifier: VR Vive
          subject:
            identifier: eagle
          session:
            identifier: Trial One
            startedAt: '2020-02-14T17:04:35+0000'
            endedAt: '2020-02-14T17:10:35+0000'
          observations:
            - identifier: round1CorrectShots
              observedAt: '2020-02-14T17:04:35+0000'
              valueInteger: 1
            - identifier: round1AverageTimeToDecide
              observedAt: '2020-02-14T17:04:36+0000'
              valueInteger: 1
            - identifier: round1ArousalAverage
              observedAt: '2020-02-14T17:04:37+0000'
              valueDecimal: 4.4
            - identifier: round1LowestArousal
              observedAt: '2020-02-14T17:04:38+0000'
              valueDecimal: 8.9
            - identifier: finalScore
              observedAt: '2020-02-14T17:04:39+0000'
              valueDecimal: 699
      properties:
        id:
          type: string
          format: uuid
        identifier:
          type: string
          minLength: 1
          maxLength: 100
        data_producer:
          type: object
          required:
            - identifier
          properties:
            identifier:
              type: string
              minLength: 1
              maxLength: 100
        session:
          $ref: '#/components/schemas/Session'
        subject:
          $ref: '#/components/schemas/Subject'
        observations:
          type: array
          items:
            $ref: '#/components/schemas/Observation'
      required:
        - id
        - identifier
        - data_producer
        - subject
        - observations
    Subject:
      title: Subject
      type: object
      description: The subject of data collection
      x-examples:
        subject-johndoe:
          id: 64ab4faa-a733-4c8e-9a69-df9c57d8d534
          identifier: eagle
          description: A placeholder identifier for a non identified person.
      properties:
        id:
          type: string
          format: uuid
        identifier:
          type: string
          minLength: 1
          maxLength: 100
        description:
          type: string
      required:
        - id
        - identifier
    Observation:
      title: Observation
      type: object
      x-examples:
        trial-one-observation:
          id: 00bcf07e-7dd4-4266-975c-f9cb9deb9761
          identifier: round1CorrectShots
          valueInteger: 1
          observedAt: '2020-02-14T15:42:51Z'
      description: The actual data observed or derived from data observed. Exactly one of the valueX fields is required. Check examples for more information.
      properties:
        id:
          type: integer
          format: uuid
        identifier:
          type: string
          minLength: 1
          maxLength: 100
        valueInteger:
          type: integer
        valueDecimal:
          type: number
        valueString:
          type: string
        observedAt:
          type: string
          format: date-time
      required:
        - id
        - identifier
    Session:
      title: Session
      type: object
      x-examples:
        example-trial-one:
          id: 8a7f111e-b342-49eb-ba16-4b86d6bba3f5
          identifier: Trial 1
          startedAt: '2020-02-14T15:04:26Z'
          endedAt: '2020-02-14T15:14:26Z'
          authoredBy: John Doe
      description: The session within which data was collected.
      properties:
        id:
          type: string
          format: uuid
        identifier:
          type: string
          minLength: 1
          maxLength: 100
        startedAt:
          type: string
          format: date-time
        endedAt:
          type: string
          format: date-time
        authoredBy:
          type: string
      required:
        - id
        - identifier
        - startedAt
        - endedAt
  securitySchemes:
    Basic Authentication:
      type: http
      scheme: basic
    Access Tokens:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
